server:
  port: 8089

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/~/vid/database/vid-h2
      driver-class-name: org.h2.Driver
      username: sa
      password: